package com.example.desk_companion

import org.json.JSONArray
import org.json.JSONObject

data class VoiceCandidate(
    val text: String,
    val confidence: Double? = null
)

data class VoiceAudioInfo(
    val rmsDb: Double? = null,
    val isSpeechDetected: Boolean = false
)

data class VoiceLanguageInfo(
    val tag: String = "zh-TW",
    val confidenceLevel: String = "confident",
    val alternatives: List<String> = listOf("zh-CN", "en-US")
)

data class VoiceAlternativeRange(
    val startIndex: Int,
    val endIndex: Int,
    val texts: List<String>
)

object VoiceResultJsonFormatter {
    fun formatFinalResult(
        transcript: String,
        formattedTranscript: String = transcript,
        source: String = "android",
        description: String = "Single voice result generated by Android speech recognition.",
        caseId: String = "voice_result",
        sessionId: String = "voice-session-${System.currentTimeMillis()}",
        timestampMs: Long = System.currentTimeMillis(),
        candidates: List<VoiceCandidate> = listOf(VoiceCandidate(transcript)),
        audio: VoiceAudioInfo = VoiceAudioInfo(isSpeechDetected = transcript.isNotBlank()),
        language: VoiceLanguageInfo = VoiceLanguageInfo(),
        alternatives: List<VoiceAlternativeRange> = emptyList()
    ): String {
        val result = JSONObject()
            .put("caseId", caseId)
            .put("sessionId", sessionId)
            .put("eventType", "final")
            .put("timestampMs", timestampMs)
            .put("transcript", transcript)
            .put("formattedTranscript", formattedTranscript)
            .put("isFinal", true)
            .put("candidates", candidates.toCandidateJsonArray())
            .put("audio", audio.toJsonObject())
            .put("language", language.toJsonObject())
            .put("recognitionParts", JSONArray())
            .put("alternatives", alternatives.toAlternativeJsonArray())

        return JSONObject()
            .put("schemaVersion", 1)
            .put("source", source)
            .put("description", description)
            .put("results", JSONArray().put(result))
            .toString(2)
    }

    private fun List<VoiceCandidate>.toCandidateJsonArray(): JSONArray {
        val array = JSONArray()
        forEach { candidate ->
            array.put(
                JSONObject()
                    .put("text", candidate.text)
                    .put("confidence", candidate.confidence ?: JSONObject.NULL)
            )
        }
        return array
    }

    private fun VoiceAudioInfo.toJsonObject(): JSONObject {
        return JSONObject()
            .put("rmsDb", rmsDb ?: JSONObject.NULL)
            .put("isSpeechDetected", isSpeechDetected)
    }

    private fun VoiceLanguageInfo.toJsonObject(): JSONObject {
        val alternativeArray = JSONArray()
        alternatives.forEach { alternativeArray.put(it) }

        return JSONObject()
            .put("tag", tag)
            .put("confidenceLevel", confidenceLevel)
            .put("alternatives", alternativeArray)
    }

    private fun List<VoiceAlternativeRange>.toAlternativeJsonArray(): JSONArray {
        val array = JSONArray()
        forEach { alternative ->
            val texts = JSONArray()
            alternative.texts.forEach { texts.put(it) }
            array.put(
                JSONObject()
                    .put("startIndex", alternative.startIndex)
                    .put("endIndex", alternative.endIndex)
                    .put("texts", texts)
            )
        }
        return array
    }
}
